"""add matrix_id to user

Revision ID: 029f998c9556
Revises: d252d0ed86fc
Create Date: 2026-04-17 17:25:48.412798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029f998c9556'
down_revision = 'd252d0ed86fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matrix_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_matrix_id'), ['matrix_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_matrix_id'))
        batch_op.drop_column('matrix_id')

    # ### end Alembic commands ###
