"""add credential type and username

Revision ID: 0e75d981fe76
Revises: 9eb1f4ed25fa
Create Date: 2026-04-17 05:46:47.316649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e75d981fe76'
down_revision = '9eb1f4ed25fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential_type', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('credential_type')

    # ### end Alembic commands ###
