"""add review_token_budget_daily to agents

Revision ID: 203f91135c86
Revises: f565aaefec93
Create Date: 2026-04-18 06:34:25.563346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203f91135c86'
down_revision = 'f565aaefec93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_token_budget_daily', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('review_token_budget_daily')

    # ### end Alembic commands ###
