"""add objectives and heartbeat_events tables

Revision ID: 3791bc0579f5
Revises: f054519cfceb
Create Date: 2026-04-15 12:02:42.765538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3791bc0579f5'
down_revision = 'f054519cfceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('next_check_at', sa.DateTime(), nullable=True),
    sa.Column('last_progress_at', sa.DateTime(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objectives_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_objectives_next_check_at'), ['next_check_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_objectives_status'), ['status'], unique=False)

    op.create_table('heartbeat_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('tick_at', sa.DateTime(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('heartbeat_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heartbeat_events_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_heartbeat_events_tick_at'), ['tick_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heartbeat_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heartbeat_events_tick_at'))
        batch_op.drop_index(batch_op.f('ix_heartbeat_events_agent_id'))

    op.drop_table('heartbeat_events')
    with op.batch_alter_table('objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objectives_status'))
        batch_op.drop_index(batch_op.f('ix_objectives_next_check_at'))
        batch_op.drop_index(batch_op.f('ix_objectives_agent_id'))

    op.drop_table('objectives')
    # ### end Alembic commands ###
