"""add patch_proposals table

Revision ID: 83ea63105544
Revises: 892b9aad24cd
Create Date: 2026-04-13 16:35:16.475804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ea63105544'
down_revision = '892b9aad24cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patch_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('diff_text', sa.Text(), nullable=False),
    sa.Column('target_path', sa.String(length=512), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('security_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('snapshot_path', sa.String(length=512), nullable=True),
    sa.Column('test_result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patch_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patch_proposals_agent_id'), ['agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patch_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patch_proposals_agent_id'))

    op.drop_table('patch_proposals')
    # ### end Alembic commands ###
