"""add parent_run_id to runs

Revision ID: 892b9aad24cd
Revises: a7c2f43f2d7f
Create Date: 2026-04-13 16:17:23.652581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892b9aad24cd'
down_revision = 'a7c2f43f2d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_run_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_runs_parent_run_id'), ['parent_run_id'], unique=False)
        batch_op.create_foreign_key(None, 'runs', ['parent_run_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_runs_parent_run_id'))
        batch_op.drop_column('parent_run_id')

    # ### end Alembic commands ###
