"""workspace file versions

Revision ID: 931bb1b0eed7
Revises: e28d7cf5a375
Create Date: 2026-04-29 07:23:29.968638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931bb1b0eed7'
down_revision = 'e28d7cf5a375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_file_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('saved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['saved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_file_versions', schema=None) as batch_op:
        batch_op.create_index('ix_wfv_agent_file_time', ['agent_id', 'filename', 'saved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_file_versions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_file_versions_saved_at'), ['saved_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_file_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_file_versions_saved_at'))
        batch_op.drop_index(batch_op.f('ix_workspace_file_versions_agent_id'))
        batch_op.drop_index('ix_wfv_agent_file_time')

    op.drop_table('workspace_file_versions')
    # ### end Alembic commands ###
