"""add max_tool_rounds to agents

Revision ID: ac9fa914df4e
Revises: f6f05daf5e88
Create Date: 2026-04-20 07:21:17.081837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9fa914df4e'
down_revision = 'f6f05daf5e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_tool_rounds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('max_tool_rounds')

    # ### end Alembic commands ###
