"""add review_events table

Revision ID: b0fdadbb39a2
Revises: c4e1471ffa8f
Create Date: 2026-04-18 06:28:48.011979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fdadbb39a2'
down_revision = 'c4e1471ffa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('review_run_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['review_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_events_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_events_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_events_status'))
        batch_op.drop_index(batch_op.f('ix_review_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_review_events_agent_id'))

    op.drop_table('review_events')
    # ### end Alembic commands ###
