"""add review_effort to agents

Revision ID: c4e1471ffa8f
Revises: 029f998c9556
Create Date: 2026-04-18 06:16:22.684697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e1471ffa8f'
down_revision = '029f998c9556'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'review_effort', sa.SmallInteger(), nullable=False, server_default='3'
        ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('review_effort')

    # ### end Alembic commands ###
