"""add package installations

Revision ID: d252d0ed86fc
Revises: d314da8e3520
Create Date: 2026-04-17 13:04:22.871617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd252d0ed86fc'
down_revision = 'd314da8e3520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('spec', sa.String(length=512), nullable=False),
    sa.Column('installed_version', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('stderr_tail', sa.Text(), nullable=True),
    sa.Column('requested_by_run_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'name', name='uq_package_installations_agent_name')
    )
    with op.batch_alter_table('package_installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_installations_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_installations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_package_installations_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_installations_status'))
        batch_op.drop_index(batch_op.f('ix_package_installations_name'))
        batch_op.drop_index(batch_op.f('ix_package_installations_agent_id'))

    op.drop_table('package_installations')
    # ### end Alembic commands ###
