"""add codex quota snapshot

Revision ID: d314da8e3520
Revises: 0e75d981fe76
Create Date: 2026-04-17 12:56:17.426836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd314da8e3520'
down_revision = '0e75d981fe76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codex_quota_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=64), nullable=True),
    sa.Column('primary_used_percent', sa.Float(), nullable=True),
    sa.Column('primary_window_minutes', sa.Integer(), nullable=True),
    sa.Column('primary_reset_at', sa.DateTime(), nullable=True),
    sa.Column('secondary_used_percent', sa.Float(), nullable=True),
    sa.Column('secondary_window_minutes', sa.Integer(), nullable=True),
    sa.Column('secondary_reset_at', sa.DateTime(), nullable=True),
    sa.Column('credits_unlimited', sa.Boolean(), nullable=True),
    sa.Column('credits_balance', sa.String(length=64), nullable=True),
    sa.Column('raw_headers', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codex_quota_snapshots')
    # ### end Alembic commands ###
