"""agent forward_matrix_room sync_matrix_room

Revision ID: d416b07a113d
Revises: ac9fa914df4e
Create Date: 2026-04-25 09:46:49.508835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd416b07a113d'
down_revision = 'ac9fa914df4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forward_matrix_room', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sync_matrix_room', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('sync_matrix_room')
        batch_op.drop_column('forward_matrix_room')

    # ### end Alembic commands ###
