"""add approval_rules table

Revision ID: e19dbde392f4
Revises: 3791bc0579f5
Create Date: 2026-04-16 17:18:28.483669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19dbde392f4'
down_revision = '3791bc0579f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(length=512), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_rules_agent_id'), ['agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_rules_agent_id'))

    op.drop_table('approval_rules')
    # ### end Alembic commands ###
