"""agent daily budgets and patch audit chain

Revision ID: e50cc2b75744
Revises: 931bb1b0eed7
Create Date: 2026-04-29 19:11:16.357900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50cc2b75744'
down_revision = '931bb1b0eed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_token_budget', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daily_cost_budget', sa.Float(), nullable=True))

    with op.batch_alter_table('patch_proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('previous_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_patch_proposals_content_hash'), ['content_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patch_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patch_proposals_content_hash'))
        batch_op.drop_column('previous_hash')
        batch_op.drop_column('content_hash')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('daily_cost_budget')
        batch_op.drop_column('daily_token_budget')

    # ### end Alembic commands ###
