"""remove oauth_profiles table and agents.oauth_profile_id

Revision ID: f054519cfceb
Revises: 83ea63105544
Create Date: 2026-04-15 05:18:14.715134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f054519cfceb'
down_revision = '83ea63105544'
branch_labels = None
depends_on = None


def upgrade():
    # Drop FK on agents first so oauth_profiles can be dropped without CASCADE.
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('agents_oauth_profile_id_fkey'), type_='foreignkey')
        batch_op.drop_column('oauth_profile_id')
    op.drop_table('oauth_profiles')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('agents_oauth_profile_id_fkey'), 'oauth_profiles', ['oauth_profile_id'], ['id'])

    op.create_table('oauth_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('account_label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('encrypted_tokens', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('refresh_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('oauth_profiles_pkey'))
    )
    # ### end Alembic commands ###
