"""add findings_json to review_events

Revision ID: f565aaefec93
Revises: b0fdadbb39a2
Create Date: 2026-04-18 06:31:01.730433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f565aaefec93'
down_revision = 'b0fdadbb39a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('findings_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.drop_column('findings_json')

    # ### end Alembic commands ###
